### ISSUE TITLE
error "Parameter format is not in query string"

### ISSUE THREAD

**Issue by stefan5588** [C0D3D3V/Ebsco-Downloader#6]
I get the following error, although the URL is valid (w/ "format=EK" at the end), please help:

Traceback (most recent call last):
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\ebsco_dl\main.py", line 184, in main
    EbscoDownloader(storage_path, args.url[0], skip_cert_verify).run()
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\ebsco_dl\ebsco_downloader.py", line 134, in run
    book_format=self.from_query(parsed_query, 'format'),
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\ebsco_dl\ebsco_downloader.py", line 105, in from_query
    raise ValueError(
ValueError: Parameter format is not in query string. Please check that you use a valid URL.

Exception: Parameter format is not in query string. Please check that you use a valid URL.
'vid' is not recognized as an internal or external command,
operable program or batch file.
Invalid drive specification.

**Comment by C0D3D3V** [comment]
Use quotation marks around the URL

**Comment by stefan5588** [comment]
aaa, fantastic! Thanks! ❤️❤️
